version: "3.1"
language: en
pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: DIETClassifier
  epochs: 100
policies:
- name: MemoizationPolicy
- name: RulePolicy
- name: TEDPolicy
  epochs: 100
assistant_id: 20250408-122216-coped-tiger
